version: '3.8'

services:
  rpr-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Bitbucket configuration - set these in your .env file or pass them directly
      - BITBUCKET_URL=${BITBUCKET_URL}
      - BITBUCKET_USERNAME=${BITBUCKET_USERNAME}
      - BITBUCKET_PASSWORD=${BITBUCKET_PASSWORD}
    # Optionally mount .env file
    # env_file:
    #   - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
